### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by tryallthethings**
Added Installation step and how to access Diceware in Password Generator

### CODE REVIEW

**Comment by tryallthethings** [comment]
Thank you for this cool plugin! 👍
Since I struggled with installing and finding the plugin afterwards, I added some information to the README. Tried to match text and screenshot style. 😄 
Feel free to make any changes necessary. And if it's any concern to you: You can do whatever you want with the screenshot (legally speaking).

Thanks
Stefan

**Comment by nitz** [comment]
This is super cool of you to do, Stefan!

I really appreciate you adding this info, as it's something I certainly hadn't considered when initially sharing.

Should be merged and live now!

Thanks so much!

**Comment by nitz** [comment]
Also wait, did you even match my windows theming for the screenshot?! You really did go above and beyond :slightly_smiling_face:

**Comment by tryallthethings** [comment]
> Also wait, did you even match my windows theming for the screenshot?! You really did go above and beyond 🙂
Yes, of course 😄 But I was too lazy to figure out your exact settings, so I used a little Paint magic.

**Pull request merged**
